server:
  port: 8081
spring:
  application:
    name: aulao-spring-security
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: <nome da aplicacao client no keycloak>
            client-secret: <secret da aplicacao>
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: <endereco do keycloak no realm correspondente>
      resourceserver:
        jwt:
          issuer-uri: <endereco do keycloak no realm correspondente>
